dist: trusty

language: node_js

node_js:
  - 10

services:
  - docker

before_install:
  - docker swarm init

script:
  - bin/e2e generate -n test1 -c 3
  - sudo chmod +x dist/test1/docker*
  - cd dist/test1 && ./docker-init.sh && ./docker-start.sh && cd ../..
  - bin/e2e run-tests -n test1 -s scenario1

after_script:
  - curl -X POST -T dist/test1/node0/ark.log.* https://logs-01.loggly.com/bulk/c700b018-aae3-448e-ad79-11dacb23da48/tag/file_upload;
  - curl -X POST -T dist/test1/node0/errors.log https://logs-01.loggly.com/bulk/c700b018-aae3-448e-ad79-11dacb23da48/tag/file_upload;
  - curl -X POST -T dist/test1/node1/ark.log.* https://logs-01.loggly.com/bulk/c700b018-aae3-448e-ad79-11dacb23da48/tag/file_upload;
  - curl -X POST -T dist/test1/node1/errors.log https://logs-01.loggly.com/bulk/c700b018-aae3-448e-ad79-11dacb23da48/tag/file_upload;
  - curl -X POST -T dist/test1/node2/ark.log.* https://logs-01.loggly.com/bulk/c700b018-aae3-448e-ad79-11dacb23da48/tag/file_upload;
  - curl -X POST -T dist/test1/node2/errors.log https://logs-01.loggly.com/bulk/c700b018-aae3-448e-ad79-11dacb23da48/tag/file_upload;

cache:
  directories:
    - node_modules

git:
  depth: 1
