dist: trusty

language: node_js

node_js:
  - 10

services:
  - docker

before_install:
  - docker swarm init

script:
  - bin/e2e generate -n test1 -c 3
  - sudo chmod +x dist/test1/docker*
  - cd dist/test1 && ./docker-init.sh && ./docker-start.sh && cd ../..
  - bin/e2e run-tests -n test1 -s scenario1

after_script:
  - cat dist/test1/node0/ark.log.*
  - cat dist/test1/node0/output.log
  - cat dist/test1/node0/errors.log
  - cat dist/test1/node1/ark.log.*
  - cat dist/test1/node1/output.log
  - cat dist/test1/node1/errors.log
  - cat dist/test1/node2/ark.log.*
  - cat dist/test1/node2/output.log
  - cat dist/test1/node2/errors.log

cache:
  directories:
    - node_modules

git:
  depth: 1
