version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install nvm
          command: |
            source ~/.bashrc
            nvm install 10
      - run:
          name: Check nodejs version
          command: |
            source ~/.bashrc
            nvm use 10
            node --version
      - run:
          name: Docker swarm init
          command: 'docker swarm init'
      - run:
          name: Npm install
          command: 'npm install'
      - run:
          name: Generate files
          command: |
            source ~/.bashrc
            nvm use 10
            node --version
            bin/e2e generate -n test1 -c 3
      - run:
          name: Make scripts executable
          command: 'sudo chmod +x dist/test1/docker*'
      - run:
          name: Docker init and start
          command: 'cd dist/test1 && ./docker-init.sh && ./docker-start.sh && cd ../..'
      - run:
          name: Run tests
          command: |
            source ~/.bashrc
            nvm use 10
            node --version
            bin/e2e run-tests -n test1 -s scenario1
      - run:
          name: Output results
          command: 'tail --lines 2000 dist/test1/node0/output.log'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
